In [1]:
import numpy as np

In [2]:
a = np.array([[1, 23, 3], [1, 2, 4]])
print(a)

[[ 1 23  3]
 [ 1  2  4]]


In [3]:
# All 0 matrix
np.zeros((2, 3,))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [4]:
np.ones((4, 2, 2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [5]:
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [6]:
b = np.full_like(a, 4)
print(b)

[[4 4 4]
 [4 4 4]]


In [7]:
np.random.random_sample(a.shape)

array([[0.2499169 , 0.88194274, 0.01170033],
       [0.0876079 , 0.21039349, 0.50954555]])

In [8]:
np.random.randint(1, 5, size=(3, 3))

array([[3, 4, 2],
       [3, 3, 3],
       [4, 1, 1]], dtype=int32)

In [9]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [10]:
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [11]:
result = np.ones((5, 5))
print(result)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [12]:
result_2 = np.zeros((3, 3))
result_2[1, 1] = 9
print(result_2)

[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [13]:
result[1:4, 1:4] = result_2
print(result)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [14]:
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [15]:
b = a.copy()
print(b)

[1 2 3]


In [16]:
b[0] = 100
print(b)
print(a)

[100   2   3]
[1 2 3]


In [17]:
a = np.array([1,  2, 3, 4])
print(a)

[1 2 3 4]


In [18]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [19]:
a = np.ones((2, 3))
b = np.full((3, 2), 2)
print(a)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [20]:
np.matmul(a, b)

array([[6., 6.],
       [6., 6.]])

In [21]:
c = np.identity(3)
np.linalg.det(c)

np.float64(1.0)

In [23]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [36]:
np.min(stats, axis=0)

array([1, 2, 3])

In [41]:
np.max(stats, axis=0)

array([4, 5, 6])

In [47]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)
after = before.reshape((2, 2, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [72]:
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])
np.stack([v1, v2, v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [69]:
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))
print(h1)
print(h2)
np.hstack((h1, h2))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

In [90]:

file_data = np.genfromtxt('data.txt', delimiter=',')
print(file_data.astype('int32'))
print("")

print(file_data)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]


In [95]:
file_data > 50
file_data[file_data > 50]

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [96]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1, 2, 8]]

array([2, 3, 9])

In [101]:
np.all(file_data > 50, axis=1)

array([False, False, False])

In [103]:
((file_data > 50) & (file_data < 100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [111]:
a = np.zeros((6, 5), dtype='int')
count = 1
for i in range(0, 6):
    for j in range(0, 5):
        a[i, j] = count
        count = count+1
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]


In [123]:
temp = a[2:4, 0:2]
temp

array([[11, 12],
       [16, 17]])

In [127]:
temp = a[[0, 1, 2, 3], [1, 2, 3, 4]]
temp

array([ 2,  8, 14, 20])

In [131]:
np.stack([a[0, 3:5], a[4, 3:5], a[5, 3:5]])
# a[0, 3:5]

array([[ 4,  5],
       [24, 25],
       [29, 30]])

In [132]:
a[[0, 4, 5], 3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])